// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvwyuskztrudwjvcungn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2d3l1c2t6dHJ1ZHdqdmN1bmduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ1ODQwOTgsImV4cCI6MjA4MDE2MDA5OH0.KTtIl6c5o_Csyzj2NaZrw3w-VESyPrSxFF8N7EOCOJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});